name: .NET Build

on:
  pull_request:
    branches: 
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    
    - name: Build the project
      run: dotnet build BucStop
      
    - name: Start BucStop
      run: |
        dotnet run --project BucStop/BucStop.csproj --urls "https://localhost:7182" &
        sleep 30

    - name: Check application status
      run: curl -k https://localhost:7182 || echo "Application did not respond as expected."
        
    - name: Run Regression Tests
      run: dotnet test BucStop/BucStop.csproj
