name: .NET Build and Test

on:
  pull_request:
    branches: 
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    
    - name: Build the project
      run: dotnet build BucStop
      
    - name: Start BucStop
      run: dotnet run --project BucStop/BucStop.csproj --urls "https://localhost:7182/"

    # Wait for the application to be ready before proceeding
    - name: Wait for BucStop to start
      run: |
        sleep 10 # Adjust sleep time as needed
        curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 60 --retry-all-errors http://localhost:7182/

    - name: Run Regression Tests
      run: dotnet test BucStop/BucStop.csproj
