name: .NET Build

on:
  pull_request:
    branches: 
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    
    - name: Build the project
      run: dotnet build BucStop
      
    - name: Start BucStop
      run: dotnet run --project BucStop/BucStop.csproj &
      # The & at the end runs the command in the background.
      # Make sure to adjust the path to where your main project is located.

    - name: Wait for BucStop to be ready
      run: |
        while ! curl --output /dev/null --silent --head --fail http://localhost:5000; do
          echo "Waiting for BucStop to be ready..."
          sleep 5
        done
      # Adjust the URL to the one BucStop listens on. This step assumes BucStop starts a web server.

    - name: Run Regression Tests
      run: dotnet test BucStop/tests
      # Adjust the path to your test project as necessary.
