name: .NET Build

on:
  pull_request:
    branches: 
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    
    - name: Build the project
      run: dotnet build BucStop
      
    - name: Start BucStop
      run: |
        dotnet run --project BucStop/BucStop.csproj --urls "https://localhost:7182/" &
        echo "Waiting for BucStop to start..."
        while ! curl --output /dev/null --silent --head --fail https://localhost:7182/; do
          sleep 5
        done
      # This starts the server in the background and waits until it's responsive.

    - name: Run Regression Tests
      run: dotnet test BucStop/BucStop.csproj
