name: .NET Build

on:
  pull_request:
    branches: 
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore BucStop/BucStop.sln
    
    - name: Build the project
      run: dotnet build BucStop/BucStop.sln --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test BucStop/BucStop.sln --no-build

