name: Deploy Pipeline

on:
  push:
    branches:
      - PBI-146
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_UNAME }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./BucStop/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_UNAME }}/bucstop:latest

  aws-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        run: |
          # Create a file for the SSH private key
          echo "${{ secrets.SSH_PK }}" > ssh_key.pem
          # Secure the key file
          chmod 600 ssh_key.pem
          # Use SSH to run your deployment script on the remote server
          ssh -i ./ssh_key.pem ubuntu@${{ secrets.SSH_HOST }}
          ./redployBucstop.sh

