name: Deploy Pipeline

on:
  push:
    branches:
      - PBI-146
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_UNAME }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./BucStop/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_UNAME }}/bucstop:latest

  aws-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PK }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.UNAME }}
        run: |
          echo "${{ secrets.SSH_PK }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ env.USER_NAME }}@${{ env.HOSTNAME }} 'bash -s' << 'EOF'
            cd /home/ubuntu/<PROJECT_DIRECTORY> &&
            git checkout dev &&
            git fetch --all &&
            git reset --hard origin/dev &&
            git pull origin dev &&
            sudo npm i &&
            sudo npm run build &&
            sudo pm2 stop all &&
            sudo pm2 start ./dist/index.js
          EOF
